### ISSUE TITLE
Wrong instruction for Rubycritic gem 

### ISSUE THREAD

**Issue by diogoribeiro** [kaiomagalhaes/rails-5-base-project#1]
[https://github.com/kaiomagalhaes/rails-5-base-project#rubycritic](https://github.com/kaiomagalhaes/rails-5-base-project#rubycriticl)
I guess it should be
`group :development, :test do
    gem 'rubycritic'
end
`
as shown here [https://github.com/whitesmith/rubycritic#getting-started](https://github.com/whitesmith/rubycritic#getting-started)

**Comment by kaiomagalhaes** [comment]
Fixed with:
https://github.com/kaiomagalhaes/rails-5-base-project/commit/b1e508e9e66af4e887752dc029de91bb2f28ccb5
